services:
  - type: web
    name: ai-qa-checker
    env: docker
    region: frankfurt  # or singapore/frankfurt as per your choice
    plan: free  # or starter, standard etc.
    dockerfilePath: ./Dockerfile
    buildCommand: ""
    startCommand: gunicorn -b 0.0.0.0:10000 app:app
    envVars:
      - key: OPENAI_API_KEY
        sync: false  # do NOT hardcode value here, set it manually in Render Dashboard
    autoDeploy: true
